/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LINKED_LIST_H_RPCGEN
#define _LINKED_LIST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct node {
	int data;
	struct node *next;
};
typedef struct node node;

#define Cantor 0x1234
#define sort 1

#if defined(__STDC__) || defined(__cplusplus)
#define SortLinkedList 1
extern  node * sortlinkedlist_1(node *, CLIENT *);
extern  node * sortlinkedlist_1_svc(node *, struct svc_req *);
extern int cantor_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SortLinkedList 1
extern  node * sortlinkedlist_1();
extern  node * sortlinkedlist_1_svc();
extern int cantor_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_node (XDR *, node*);

#else /* K&R C */
extern bool_t xdr_node ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LINKED_LIST_H_RPCGEN */
