/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linked_list.h"
#include "data_structures.h"


void
cantor_1(char *host)
{
	CLIENT *clnt;
	node  *sorted;
	node  *unsorted;

#ifndef	DEBUG
	clnt = clnt_create (host, Cantor, sort, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif
    

    unsorted = fillList();
	sorted = sortlinkedlist_1(unsorted, clnt);
    printList(sorted);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cantor_1 (host);
exit (0);
}
